import { describe, expect, it } from 'vitest';

import { psql, stackBeschikbaarOfFaal } from './psql-stack';

/**
 * Het auditspoor van een commitment heeft een sleutel die niet kan knopen — QS8-303.
 *
 * ⚠️ **Waarom deze suite bestaat.** `tests/rls/epic9.test.ts` ging op 06-09-2026
 *    rood in `npm run poort`, op twee gevallen met dezelfde vorm — verwacht
 *    `['confirmed','triggered','posted']`, gekregen
 *    `['confirmed','posted','triggered']` — en groen bij een losse run van
 *    hetzelfde bestand op dezelfde database. Dat is geen flake maar een meting:
 *    de volgorde lag niet vast.
 *
 *    Aan één UPDATE van `commitments` hangen twee AFTER-triggers die allebei in
 *    `commitment_events` schrijven. `now()` is in Postgres gelijk aan
 *    `transaction_timestamp()` en dus constant binnen een transactie, en
 *    `commitment_events.id` is een `gen_random_uuid()`. Er wás niets om op te
 *    sorteren.
 *
 * ⚠️ **De belofte is niet "de test is groen".** De belofte is dat de eigenaar
 *    zijn eigen auditspoor in de volgorde ziet waarin het geschreven is —
 *    domeinregel 6 leunt daarop. `fetchCommitmentSpoor()` toonde de gebruiker
 *    "geplaatst in de groep" bóven "verschuldigd geworden" met precies dezelfde
 *    oorzaak.
 *
 * ## Waar deze suite ophoudt, en waar de rest staat
 *
 * Deze suite bewaakt **de sleutel**: bestaat hij, kan hij knopen, kan een client
 * hem zetten. Dat de léésvolgorde hem ook gebruikt, is een eigenschap van de
 * bron en staat in `tests/beloftes/auditspoor-volgorde.test.ts`. Dat het
 * échte pad de goede volgorde oplevert, staat in `tests/rls/epic9.test.ts`.
 * Drie grendels, drie plekken, elk apart te ijken.
 *
 * ⚠️ **Er staat hier met opzet géén aparte assertie dat twee gebeurtenissen uit
 *    één transactie een verschillende `seq` krijgen.** Dat volgt uit
 *    `generated always as identity` plus de unieke index — het is dezelfde
 *    grendel, geen tweede. Een assertie die dat nog eens los beweert, gaat rood
 *    van dezelfde mutatie en isoleert dus niets.
 *
 * ⚠️ **De grantcontrole stond hier eerst als losse test, en dat was fout.** Bij
 *    mutatie A ging hij mee rood: `has_column_privilege` werpt op een kolom die
 *    niet bestaat. Eén mutatie die twee tests rood maakt, isoleert niets. Hij is
 *    daarom tak 4 van dezelfde bewaking geworden.
 *
 * IJKING — met de hand gedraaid op 07-09-2026, mutatie per tak van
 * `volgorde_bewaking()`, elke keer op een verse stack:
 *
 *   A  `alter table commitment_events drop column seq cascade`
 *      → 1 rood: "volgordekolom seq bestaat niet"
 *   B  `alter column seq drop identity`, daarna
 *      `add generated by default as identity`
 *      → 1 rood: "volgordekolom seq is geen generated always as identity"
 *   C  `drop index commitment_events_volgorde_idx`
 *      → 1 rood: "unieke sorteerindex commitment_events_volgorde_idx ontbreekt"
 *   D  `grant insert (seq) on commitment_events to authenticated`
 *      → 1 rood: "volgordekolom seq staat in een INSERT-grant van authenticated"
 *   E  de rij uit `volgorde_register()` halen
 *      → 1 rood op de ondergrens hieronder
 *   F  `grant usage on sequence commitment_events_seq_seq to authenticated`
 *      → 1 rood: "sequence … is USAGE voor authenticated"
 *
 * ⚠️ B is de tak die het makkelijkst als overbodig voelt en het meest doet: met
 *    `by default` mag een INSERT-grant de kolom alsnog zetten, en dan is de
 *    volgorde weer iets dat een client kiest. Zie 0172 — daar kostte precies
 *    dat verschil de belofte.
 *
 * ⚠️⚠️ **Tak 5 (F) kwam uit de security-review en niet uit deze suite**, en hij
 *    is de belangrijkste van de vijf. `public` had tot migratie 0174 **nul**
 *    sequences; een identity-kolom brengt de eerste mee, en Supabase's
 *    `alter default privileges` deelt hem net zo hard uit als een tabel. 📏
 *    Gemeten vóór de reparatie: `anon USAGE=t, auth USAGE=t, auth UPDATE=t,
 *    anon SELECT=t`. `UPDATE` op een sequence is `setval()` — de teller
 *    terugzetten en het spoor draait om. Onwrikbare regel 4 in een objectsoort
 *    die deze codebase nog niet kende.
 */

const TEST_TIMEOUT = 30_000;

const beschikbaar = stackBeschikbaarOfFaal(
  "select count(*) from pg_proc where proname = 'volgorde_bewaking'",
  import.meta.url,
);

describe.skipIf(!beschikbaar)('het auditspoor heeft een sleutel die niet knoopt', () => {
  it(
    'laat geen enkele volgordesleutel uit het register kapot staan',
    async () => {
      const uit = psql(
        "select coalesce(string_agg(tabel || ': ' || bevinding, E'\\n'), '') from volgorde_bewaking()",
      );

      expect(uit.trim()).toBe('');
    },
    TEST_TIMEOUT,
  );

  it(
    'houdt een register dat niet leeg is',
    async () => {
      // ⚠️ De ondergrens. Een bewaking die niets meer te toetsen heeft, is groen
      //    om de verkeerde reden — en dat is de goedkoopste manier om deze suite
      //    per ongeluk uit te zetten: haal de rij uit `volgorde_register()` en
      //    de test hierboven blijft eeuwig groen.
      const uit = psql('select count(*) from volgorde_register()');

      expect(Number(uit.trim())).toBeGreaterThan(0);
    },
    TEST_TIMEOUT,
  );

  it(
    'noemt bij elke rij in het register een reden',
    async () => {
      // ⚠️ Zelfde vorm als `definer_uitzonderingen()` in 0167: een register
      //    zonder reden is over een half jaar een regel die niemand meer durft
      //    weg te halen.
      const uit = psql(
        "select coalesce(string_agg(tabel, ', '), '') from volgorde_register() where coalesce(reden, '') = ''",
      );

      expect(uit.trim(), 'deze registerrijen dragen geen reden').toBe('');
    },
    TEST_TIMEOUT,
  );

});
